var $ui = $ui || {};
/**
Create a new select control. Controls can be converted from existing `select` or `ul` elements, or generated by passing an `options` parameter

HTML

	<!-- Generate from an existing element -->
	
    <select id='selectFromEl'>
        <option value='val1'>
            option 1
        </option>
        <option value='val2'>
            option 2
        </option>
        <option value='val3'>
            option 3
        </option>
        <option value='val4'>
            option 4
        </option>
        <option value='val5'>
            option 5
        </option>
    </select>
	
	<!-- Generate from passing an options object -->
	
	<div id='selectFromObject'></div>

Javascript
	
	// Single select with no dropdown and pre-selected value
	
	$ui.select({
		element: document.getElementById('selectFromEl'),
		value: 'val3'
	});	
	
	// Multiple select with dropdown
	
	$ui.select({
		element: document.getElementById('selectFromObject'),
		options:[
			{
				value:'val1',
				name:'value 1'
			},
			{
				value:'val2',
				name:'value 2'
			},
			{
				value:'val3',
				name:'value 3'
			},
			{
				value:'val4',
				name:'value 4'
			},
			{
				value:'val5',
				name:'value 5'
			},
		]
	});	
		
	
@class $ui.select
@constructor
@param options {Object}
@param options.element {Object} DOM element to convert to control
@param options.options {Array} Object array of control options
@param options.options.value {String} Option value
@param options.options.name {String} Option name (displayed label)
@param options.options.selected {Boolean} Option selected state
@param [options.value=0] {String} Value of initially selected option, defaults to the attribute value set on the passed element, or `0`
@param [options.name=ui-select-RandInt] {String} Name of underlying input control, defaults to the attribute value set on the passed element, or `ui-select-RandInt`
@param [options.placeholder=string] {String} Placeholder when no options selected, defaults to the attribute value set on the passed element, or `Please select...`
@param [options.multiple=false] {Boolean} Whether to allow multiple options to be selected, defaults to the attribute value set on the passed element, or `false`
@param [options.dropdown=false] {Boolean} Display options in dropdown list
@param [options.tabindex=0] {Number} Tabindex of control, defaults to the attribute value set on the passed element, or `0`
@param [options.disabled=false] {Boolean} Disabled state of control, defaults to the attribute value set on the passed element, or `false`
@return Object {Object} Consisting of original DOM element (item `0`) and class methods (see below)
@chainable
*/
(function($ui) {
    $ui.select = function(opt) {

        var el = opt.element,
            options = opt.options || [],
            inputValue = opt.value || $ui.attribute(el, 'value') || [],
            inputName = opt.name || $ui.attribute(el, 'name') || 'ui-select-' + $ui.getRand(1, 999),
            dropdown = Boolean(opt.dropdown),
            inputMultiple = (Boolean(opt.multiple) === true || $ui.attribute(el, 'multiple')) ? true : false,
            inputPlaceholder = opt.placeholder || $ui.attribute(el, 'placeholder') || 'Please select...',
            // listeners=opt.listeners === undefined ? {} : opt.listeners,            
            inputDisabled = (opt.disabled || el.getAttribute('disabled')) ? 'disabled' : '',
            inputTabIndex = opt.tabindex || el.getAttribute('tabindex') || 0;

        inputName = (inputMultiple && inputName.indexOf('[]') === -1) ? inputName + '[]' : inputName.replace('[]', '');

        // input value is now an array
        inputValue = $ui.toArr(inputValue);

        // populate options if none present and the underlying element is SELECT or UL
        if (options.length === 0 && (el.nodeName === "SELECT" || el.nodeName === "UL")) {
            for (var i = 0; i < el.children.length; i++) {
                var oVal = $ui.attribute(el.children[i], 'value'),
                    oName = el.children[i].innerHTML;
                oVal = oVal || oName;
                if ($ui.attribute(el.children[i], 'selected') && inputValue.indexOf(oVal) === -1) {
                    inputValue.push(oVal);
                }
                options.push({
                    name: oName,
                    value: oVal
                });
            }
        }

        /*jshint multistr:true */
        var tpl = "<div class='ui-select " + (inputMultiple ? 'ui-select-multiple' : '') + " " + (dropdown ? 'ui-select-dropdown' : '') + " " + (inputDisabled ? 'ui-disabled' : '') + "' tabindex='" + inputTabIndex + "'>\
                <input type='hidden' name='" + inputName + "'/>\
                <div class='ui-select-value " + (!inputValue || inputValue.length < 1 ? 'ui-placeholder' : '') + "'>sdsd</div>\
            <ul>";
        for (var o = 0; o < options.length; o++) {
            tpl += "<li class='ui-option' data-value='" + options[o].value + "'>" + options[o].name + "</li>";
        }
        tpl += "</ul></div>";

        el.innerHTML = '';
        el = $ui.replaceEl(el, tpl);

        var triggerEl = el.children[1],
            inputEl = el.children[0],
            optionsEl = el.children[2];

        if (dropdown && !inputDisabled) {
            var overlayEl = document.body.insertBefore($ui.createEl("<div class='ui-overlay'></div>"), document.body.children[0]);
            $ui.bindEvent('click', overlayEl, function() {
                $ui.removeClass(overlayEl, 'ui-show');
                $ui.toggleClass(el, 'ui-show');
            });
            $ui.bindEvent('click', el, function(e) {

                if ($ui.attribute(e.target, 'data-value') && $ui.hasClass(e.target, 'ui-select-value-tag')) {
                    inputValue = $ui.collide(inputValue, $ui.attribute(e.target, 'data-value'), 2);
                    updateValue();
                }


                if ($ui.hasClass(e.target, 'ui-select-value-tag') || (inputMultiple && $ui.hasClass(e.target, 'ui-option')) || !$ui.hasClass(el, 'ui-show')) {
                    $ui.addClass(overlayEl, 'ui-show');
                    $ui.addClass(el, 'ui-show');
                } else {
                    $ui.removeClass(overlayEl, 'ui-show');
                    $ui.removeClass(el, 'ui-show');
                }

            });
        }


        function updateValue() {
            var valueHTML = '';
            if (!inputMultiple) {
                inputValue.splice(1, inputValue.length - 1);
            }
            for (var o = 0; o < options.length; o++) {
                options[o].selected = (inputValue.indexOf(options[o].value) !== -1) ? true : false;
                $ui.toggleClass(optionsEl.children[o], 'ui-selected', options[o].selected);
                if (options[o].selected) {
                    valueHTML = inputMultiple ? valueHTML += "<span class='ui-select-value-tag' data-value='" + options[o].value + "'>" + options[o].name + "</span>" : options[o].name;
                }
            }
            triggerEl.innerHTML = valueHTML ? valueHTML : inputPlaceholder;
            if (inputValue.length < 1) {
                $ui.addClass(triggerEl, 'ui-placeholder');
            } else {
                $ui.removeClass(triggerEl, 'ui-placeholder');
            }
            // update underlying input element
            inputEl.value = inputMultiple ? inputValue : inputValue.join('');
        }
        if (!inputDisabled) {
            $ui.bindEvent('click', optionsEl, function(e) {
                if (e.target.nodeName === "LI") {
                    inputValue = inputMultiple ? $ui.collide(inputValue, options[$ui.getIndex(e.target)].value, 3) : $ui.collide(inputValue, options[$ui.getIndex(e.target)].value);
                    updateValue();
                }
            });
        }
        updateValue();
        return {
            0: el
        };
    };
    return $ui;
})($ui);
